language: csharp
mono: none
dotnet: 3.0.100
install:
- dotnet restore
script:
- xbuild ./XamarinMobileApp/XamarinMobileApp.sln
- xbuild ./StolovkaWebAPI/StolovkaWebAPI.sln
- dotnet test ./StolovkaWebAPI/StolovkaWebAPI.Tests/StolovkaWebAPI.Tests.csproj
- dotnet test ./XamarinMobileApp/XamarinMobileApp.Tests/XamarinMobileApp.Tests.csproj