language: csharp
solution: "./XamarinMobileApp/XamarinMobileApp.sln"
solution: "./StolovkaWebAPI/StolovkaWebAPI.sln"
mono: none
dotnet: 3.0.0
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./XamarinMobileApp/XamarinMobileApp.sln
- dotnet restore
script:
- xbuild ./XamarinMobileApp/XamarinMobileApp.sln
- xbuild ./StolovkaWebAPI/StolovkaWebAPI.sln
- dotnet test ./StolovkaWebAPI/StolovkaWebAPI.Tests/StolovkaWebAPI.Tests.csproj
- dotnet test ./XamarinMobileApp/XamarinMobileApp.Tests/XamarinMobileApp.Tests.csproj