language: csharp
mono: none
dotnet: 3.0.100
before_install:
- sudo apt-get update
- sudo apt-get install mono-complete mono-xbuild
install:
- dotnet restore ./StolovkaWebAPI
script:
- xbuild ./XamarinMobileApp/XamarinMobileApp.sln
- xbuild ./StolovkaWebAPI/StolovkaWebAPI.sln
- dotnet test ./StolovkaWebAPI/StolovkaWebAPI.Tests/StolovkaWebAPI.Tests.csproj
- dotnet test ./XamarinMobileApp/XamarinMobileApp.Tests/XamarinMobileApp.Tests.csproj